server:
    port: 9090
spring:
    application:
        name: JWT-SERVICE
    datasource:
        driver-class-name: org.postgresql.Driver
        password: admin
        url: jdbc:postgresql://localhost/auth-service
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/